# Generated by Django 2.1.7 on 2019-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('email1', models.EmailField(max_length=100)),
                ('mobile1', models.IntegerField()),
                ('order1', models.CharField(max_length=20)),
                ('actype1', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=300)),
            ],
        ),
    ]
